### ISSUE TITLE
General fixes

### ISSUE THREAD

**Issue by abdelazizElemary** [EmilMourad/Udemy#1]
- Fix heights and widths all over the page to be as similar as possible to udemy.com in buttons and images and everywhere
- Don't take the course as images. You have to take only the image of the course. place the description and star rating as html components.
- also in the header make it responsive. the image and the card should be beside each other until the window is so small.
<img width="1440" alt="Screen Shot 2022-08-11 at 4 42 22 PM" src="https://user-images.githubusercontent.com/25887879/184160318-c257dd9d-78e4-4c28-a3fc-65394b43e7ce.png">

**Comment by EmilMourad** [comment]
Issues have been resolved
